### PR TITLE
[feat]: Add contribution guidelines

### PR DESCRIPTION
**Pull request by kabugatti**

### CODE REVIEW

**Comment by kabugatti** [comment]
closes #2

**Comment by kabugatti** [comment]
Hey @JunDevHarsh , finished up on the guidelines, let me know what you think

**Comment by itsxharsh** [comment]
Hello @grand-rick001, I was going through your PR and saw that you have put more than I expected. But there are some reasons that I am not able to merge this PR to `dev` branch because you have made an extra commit after making a PR. Please avoid updating your branch after making a PR to any project. Or you can update your branch first and make a commit and raise a PR after that.

**Comment by itsxharsh** [comment]
Please reply if you want to work on this issue again. If yes then I am closing this PR and will expect to create a PR after making changes to the code.

**Comment by kabugatti** [comment]
Okay, noted. Just to be clear, you want to close the PR so I can make changes, then re-open it?

**Comment by itsxharsh** [comment]
Okay, I am closing this PR right now. Then you have to  make another PR reference to this issue.

**Comment by kabugatti** [comment]
No problem

**Pull request closed without merging**
